[[Anime]]
Title = "轻音少女"
ImageUrl = "./images/动漫/轻音少女.png"
Rating = 5.0
Description = "讲述了樱丘高中轻音部的故事，描绘了少女们追逐音乐梦想的温馨日常"
UserReview = "只是觉得女孩子们之间真好啊"

[[Anime]]
Title = "请问你要来点兔子吗"
ImageUrl = "./images/动漫/请问你要来点兔子吗.png"
Rating = 5.0
Description = "在充满咖啡香气的兔子咖啡馆里，少女们展开了一段温馨治愈的故事"
UserReview = "萌系至高之作"

[[Anime]]
Title = "悠哉日常大王"
ImageUrl = "./images/动漫/悠哉日常大王.png"
Rating = 5.0
Description = "描绘了乡村学校中少女们的悠闲日常，充满欢笑与温情"
UserReview = "描述了一份美好的乡村生活"

[[Anime]]
Title = "珈百璃的坠落"
ImageUrl = "./images/动漫/珈百璃的坠落.png"
Rating = 5.0
Description = "天使珈百璃来到人间后沉迷游戏，展开了一系列搞笑的故事。"
UserReview = ""

[[Anime]]
Title = "登山少女"
ImageUrl = "./images/动漫/向山进发.png"
Rating = 4.8
Description = ""
UserReview = ""

[[Anime]]
Title = "孤独摇滚"
ImageUrl = "./images/动漫/孤独摇滚.png"
Rating = 4.9
Description = "社恐少女后藤一里组建乐队，在音乐中寻找自我的故事。"
UserReview = "暂无"

[[Anime]]
Title = "放学后的海堤日记"
ImageUrl = "./images/动漫/放学后的海堤日记.png"
Rating = 4.7
Description = "钓鱼社团的日常"
UserReview = ""

[[Anime]]
Title = "打了300年的史莱姆，不知不觉就练到了满级"
ImageUrl = "./images/动漫/史莱姆.png"
Rating = 4.8
Description = ""
UserReview = ""

[[Anime]]
Title = "女孩的钓鱼慢活"
ImageUrl = "./images/动漫/女孩的钓鱼慢活.png"
Rating = 4.6
Description = ""
UserReview = ""

[[Anime]]
Title = "黄金拼图"
ImageUrl = "./images/动漫/黄金拼图.png"
Rating = 5.0
Description = ""
UserReview = ""

[[Anime]]
Title = "街角魔族"
ImageUrl = "./images/动漫/街角魔族.png"
Rating = 4.6
Description = ""
UserReview = ""